- name: Deploying servers on AWS with CloudFormation
  hosts: servers
  connection: local
  gather_facts: False
  become: no
  vars_files:
    - "../inventory/group_vars/all_vars.yml"
    - "../inventory/group_vars/servers_vars.yml"
  tasks:
    #This task is neccessary to work with dynamic inventory and
    #provide group_vars before actually provisioning
    - name: Add localhost to the group
      add_host:
        name: localhost
        groups: servers
      tags:
        - always

    - name: Provisioning in AWS using cloudformation template
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "{{ aws_region }}"
        disable_rollback: true
        template: "../files/servers.cf.template.yml"
        template_parameters:
          Image: "{{ aws_image }}"
          KeyPairName: "{{ aws_key_name }}"
          InstanceType: "{{ aws_instancetype }}"
          EnvId: "{{ env_id }}"
          RootVolumeName: "{{ disks[0].device_name }}"
          RootVolumeType: "{{ disks[0].type }}"
          RootVolumeSize: "{{ disks[0].size }}"
          ServerDomain: "{{ dns_domain }}"
          ServerName: "{{ server_name }}"
          ServerName2: "{{ server_name2 }}"
          AwsZone: "{{aws_zone}}"
          AwsZone2: "{{aws_zone2}}"
          EBSkey: "{{ebs_key}}"
          Subnet: "{{subnet}}"
          Subnet2: "{{subnet2}}"
          PrivateRoute53HostedZone: "{{private_hosted_zone}}"
          VPC: "{{vpc_id}}"
      when: hosting_infrastructure == "aws"
    
    - name: Delete existing AWS cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "absent"
        region: "{{ aws_region }}"
        disable_rollback: true
      tags:
        - never
        - deletestack
